-- MySQL Script generated by MySQL Workbench
-- Thu Jan 12 15:17:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema idata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idata` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `idata` ;

-- -----------------------------------------------------
-- Table `idata`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`categories` (
  `category_id` VARCHAR(50) NOT NULL,
  `category_name` VARCHAR(50) NOT NULL,
  `category_image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`permissions` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`products` (
  `product_id` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(100) NOT NULL,
  `product_description` VARCHAR(255) NULL DEFAULT NULL,
  `product_price` INT NOT NULL,
  `product_image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`product_categories` (
  `product_id` VARCHAR(50) NOT NULL,
  `category_id` VARCHAR(50) NOT NULL,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `product_categories_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `idata`.`products` (`product_id`),
  CONSTRAINT `product_categories_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `idata`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`role_permissions` (
  `role_permission_id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`role_permission_id`),
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  INDEX `permission_id` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `role_permissions_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `idata`.`roles` (`role_id`),
  CONSTRAINT `role_permissions_ibfk_2`
    FOREIGN KEY (`permission_id`)
    REFERENCES `idata`.`permissions` (`permission_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`users` (
  `user_id` VARCHAR(50) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `idata`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idata`.`user_roles` (
  `user_role_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(50) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_role_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user_roles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `idata`.`users` (`user_id`),
  CONSTRAINT `user_roles_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `idata`.`roles` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
